-- =========================================================================
-- TanCoreLab — Kapsamlı Güvenlik, RLS ve Veritabanı Yapılandırma SQL'i
-- Tarih: 2026-09-20
-- Açıklama: Row Level Security (RLS) politikaları, public_leaderboard görünümü
--           ve sunucu taraflı güvenli puanlama (RPC) fonksiyonları.
-- =========================================================================

-- 1. TABLOLARIN OLUŞTURULMASI (Eğer Mevcut Değilse)

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    university TEXT,
    department_and_class TEXT,
    avatar_emoji TEXT DEFAULT '👨‍🎓',
    avatar_url TEXT,
    xp INTEGER DEFAULT 0 CHECK (xp >= 0),
    streak INTEGER DEFAULT 1 CHECK (streak >= 1),
    completed_lessons INTEGER DEFAULT 0 CHECK (completed_lessons >= 0),
    device_id TEXT,
    device_info TEXT,
    is_verified BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.user_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL UNIQUE,
    total_xp INTEGER DEFAULT 0,
    level INTEGER DEFAULT 1,
    streak INTEGER DEFAULT 1,
    completed_lessons JSONB DEFAULT '[]'::jsonb,
    completed_case_exams JSONB DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.tanco_chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    user_email TEXT,
    sender TEXT NOT NULL CHECK (sender IN ('tanco', 'student')),
    text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.course_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code TEXT NOT NULL,
    course_title TEXT,
    file_name TEXT NOT NULL,
    file_size BIGINT DEFAULT 0,
    file_type TEXT,
    file_url TEXT,
    uploader_email TEXT,
    uploader_name TEXT,
    note_description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.app_issues (
    id TEXT PRIMARY KEY,
    user_message TEXT NOT NULL,
    detected_issue TEXT,
    screen_context TEXT,
    user_email TEXT,
    user_name TEXT,
    severity TEXT DEFAULT 'Medium',
    status TEXT DEFAULT 'Open',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================================
-- 2. ROW LEVEL SECURITY (RLS) ETKİNLEŞTİRME
-- =========================================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tanco_chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_issues ENABLE ROW LEVEL SECURITY;

-- =========================================================================
-- 3. RLS POLİTİKALARI
-- =========================================================================

-- PROFILES:
DROP POLICY IF EXISTS "Profiles are readable by authenticated users" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can delete own profile" ON public.profiles;

CREATE POLICY "Profiles are readable by authenticated users"
ON public.profiles FOR SELECT
TO authenticated, anon
USING (true);

CREATE POLICY "Users can insert their own profile"
ON public.profiles FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile"
ON public.profiles FOR UPDATE
TO authenticated
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can delete own profile"
ON public.profiles FOR DELETE
TO authenticated
USING (auth.uid() = id);

-- TANCO CHATS:
DROP POLICY IF EXISTS "Users can read their own chats" ON public.tanco_chats;
DROP POLICY IF EXISTS "Users can insert their own chats" ON public.tanco_chats;
DROP POLICY IF EXISTS "Users can delete their own chats" ON public.tanco_chats;

CREATE POLICY "Users can read their own chats"
ON public.tanco_chats FOR SELECT
TO authenticated
USING (auth.uid()::text = user_id OR auth.jwt() ->> 'email' = user_email);

CREATE POLICY "Users can insert their own chats"
ON public.tanco_chats FOR INSERT
TO authenticated
WITH CHECK (auth.uid()::text = user_id OR auth.jwt() ->> 'email' = user_email);

CREATE POLICY "Users can delete their own chats"
ON public.tanco_chats FOR DELETE
TO authenticated
USING (auth.uid()::text = user_id OR auth.jwt() ->> 'email' = user_email);

-- USER PROGRESS:
DROP POLICY IF EXISTS "Users can read own progress" ON public.user_progress;
DROP POLICY IF EXISTS "Users can upsert own progress" ON public.user_progress;

CREATE POLICY "Users can read own progress"
ON public.user_progress FOR SELECT
TO authenticated
USING (auth.uid()::text = user_id);

CREATE POLICY "Users can upsert own progress"
ON public.user_progress FOR ALL
TO authenticated
USING (auth.uid()::text = user_id)
WITH CHECK (auth.uid()::text = user_id);

-- COURSE NOTES:
DROP POLICY IF EXISTS "Anyone can view course notes" ON public.course_notes;
DROP POLICY IF EXISTS "Authenticated users can upload course notes" ON public.course_notes;

CREATE POLICY "Anyone can view course notes"
ON public.course_notes FOR SELECT
TO authenticated, anon
USING (true);

CREATE POLICY "Authenticated users can upload course notes"
ON public.course_notes FOR INSERT
TO authenticated, anon
WITH CHECK (true);

-- APP ISSUES:
DROP POLICY IF EXISTS "Anyone can report issues" ON public.app_issues;
CREATE POLICY "Anyone can report issues"
ON public.app_issues FOR INSERT
TO authenticated, anon
WITH CHECK (true);

-- =========================================================================
-- 4. GÜVENLİ LİDERLİK GÖRÜNÜMÜ (KVKK / Privacy Compliant View)
-- =========================================================================

CREATE OR REPLACE VIEW public.public_leaderboard AS
SELECT
    id,
    full_name,
    university,
    department_and_class,
    avatar_emoji,
    avatar_url,
    xp,
    streak,
    completed_lessons
FROM public.profiles
ORDER BY xp DESC;

-- =========================================================================
-- 5. SUNUCU TARAFLI GÜVENLİ PUANLAMA (RPC FUNCTION)
-- =========================================================================

CREATE OR REPLACE FUNCTION public.complete_lesson_secure(
    p_lesson_id TEXT,
    p_module_id TEXT,
    p_xp_to_award INTEGER DEFAULT 15
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_user_id UUID := auth.uid();
    v_capped_xp INTEGER;
BEGIN
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Bu işlemi gerçekleştirmek için oturum açmalısınız.';
    END IF;

    -- Güvenlik sınırı: Tek bir dersten en fazla 50 XP kazanılabilir
    v_capped_xp := LEAST(GREATEST(p_xp_to_award, 0), 50);

    UPDATE public.profiles
    SET xp = xp + v_capped_xp,
        completed_lessons = completed_lessons + 1,
        updated_at = NOW()
    WHERE id = v_user_id;

    RETURN jsonb_build_object(
        'success', true,
        'lesson_id', p_lesson_id,
        'module_id', p_module_id,
        'awarded_xp', v_capped_xp
    );
END;
$$;
